# Generated by Django 6.1.1 on 2026-09-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_demopost_demotask_democomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.CharField(help_text='Email address or Telegram username (e.g. @username)', max_length=150, verbose_name='Email or Telegram'),
        ),
    ]
